modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="sobr"
version="v0.a2"
displayName="Spires of Baedoor"
credits="Toma400 (author), DylanVhs (textures), MCreator (created with)"
displayURL="https://discord.gg/GbTw9KqnrE"
authors="Toma400"
description='''
Standalone expansion for Wastelands of Baedoor mod. Adds a lot more lore elements, magic and herbalist system
'''

[[dependencies.sobr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




